# Generated by Django 5.1 on 2024-09-15 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrowing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 9, 29)),
        ),
    ]
