# Generated by Django 5.1 on 2024-09-15 13:24

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_borrowing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=books.models.default_due_date),
        ),
    ]
